# application properties

logging:
  level:
    root: INFO
    com:
      scurtis: INFO

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql


